on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  opal:
    name: Run OPAL workflow for sourmash
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: opal
          environment-file: environment.yml
      - name: Run snakemake pipeline
        shell: bash -l {0}
        run: snakemake --use-conda outputs/cami_i_low/opal_output_all/results.html outputs/cami_ii_mg/opal_output_all/results.html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v2.10.1
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: outputs/
